export const data = [
  {
    key: 1,
    name: "Hackathon",
    prize: "₹ 60000",
    Imgsrc: require("./files/hackathon.webp"),
    link: "https://www.nitj.ac.in/events_registration/hackmol/login",
    visit: "https://hackmol.tech/",
    desc: "HackMOL is the flagship annual 30-hour hackathon being organised by GDSC of NIT J...",
  },
  {
    key: 2,
    name: "Fashion Show",
    prize: "₹ 30000",
    Imgsrc: require("./files/fashion.webp"),
    link: "https://forms.gle/1yoLPcBeK3oidNxC9",
    visit: "event/fashionshow",
    desc: "Fashion show organised by NITJ is one of the most awaited and celebrated events of TechNITi ....",
  },
  {
    key: 3,
    name: "NITYaan",
    prize: "Goodies+",
    Imgsrc: require("./files/nityaan.webp"),
    link: "register",
    visit: "event/nityaan",
    desc: "NIT, Jalandhar is back with NITYAAN, catered to quench the thirst of rocket enthusiasm among...",
  },
  {
    key: 4,
    name: "robowar",
    prize: "₹ 50000",
    Imgsrc: require("./files/robowars.webp"),
    link: "register",
    visit: "event/robowar",
    desc: "It will be a savage, Clash of Metals with the alloys grinding red hot. It is a game of style,   ...",
    name: "uavdrone",
    prize: "₹ 35000",
    Imgsrc: require("./files/UAVdrone.webp"),
    link: "",
    visit: "uavdrone",
    desc: "Drones are objects that the world is looking up to. TechNITi'23 presents the UAV Drone challange, A multi-level ...",
  },
  {
    key: 5,
    name: "gaNIT",
    prize: "₹ 5500",
    Imgsrc: require("./files/maths.webp"),
    visit: "event/integrationbee",
    desc: "The Integration Bee is an annual traditional playoff-style event that has gained popularity in US colleges and universities...",
  },
  {
    key: 6,
    name: "robohunt",
    prize: "₹ 3000",
    Imgsrc: require("./files/robohunt.webp"),
    link: "",
    visit: "robohunt",
    desc: "Robo Hunt is a competition where teams will write the code of controller of small robots, known as bots, that are less than 6 kg...",
  },
  {
    key: 7,
    name: "microrobowar",
    prize: "₹ 8000",
    Imgsrc: require("./files/microrobowar.webp"),
    link: "",
    visit: "microrobowar",
    desc: "Micro Robo War is a robot fighting competition where contestant teams will compete head-to-head in a 1 vs 1 match...",
  },

  {
    key: 8,
    name: "chem-e-car",
    prize: "₹ 10000",
    Imgsrc: require("./files/chemecar.webp"),
    regvisit: "https://l01vlmq5gan.typeform.com/to/zGwKjZLG",
    visit: "chem-e-car",
    desc: "Chem-e-Car engages college students in designing and constructing a car powered by a chemical energy...",
  },
  {
    key: 9,
    name: "3BHK",
    prize: "Momentos & Goodies",
    Imgsrc: require("./files/3bhk.webp"),
    visit: "threebhk",
    desc: "The Aim of the event is to teach the students about the practical application of building construction...",
  },
  {
    key: 10,
    name: "prayaas",
    prize: "₹ 3000",
    Imgsrc: require("./files/prayaas.webp"),
    link: "",
    visit: "prayaas",
    desc: "To educate underprivileged and socially marginalized youth who lack access to education, especially those who are the...",
  },
  {
    key: 11,
    name: "chem-e-design",
    prize: "₹ 10000",
    Imgsrc: require("./files/chemedesign.webp"),
    link: "",
    visit: "chem-e-design",
    desc: "The event will be organised in two parts Designing the heat exchanger  Presenting the technical ...",
  },
  {
    key: 12,
    name: "RCcars",
    prize: "",
    Imgsrc: require("./files/rccar.webp"),
    link: "",
    visit: "rccars",
    desc: "RC car event, a fight of machines and a test of endurance, persistence and strength of the car. There will be a ...",
  },
  {
    key: 13,
    name: "atv Racing",
    prize: "",
    Imgsrc: require("./files/hackathon.webp"),
    link: "",
    visit: "avishkar",
    desc: "Our self-manufactured ATV is exhibited in fully running condition and workshop would be commanded by various...",
  },
  {
    key: 14,
    name: "CHEM-E-HUNT",
    prize: "₹ 5000",
    Imgsrc: require("./files/bestfromwaste.webp"),
    link: "",
    visit: "chem-e-hunt",
    desc: "In Chem-e-hunt, participants will receive chemical questions of numerical type and will also be supplied with the ...",
  },
  {
    key: 15,
    name: "bolt-bolt",
    prize: "₹ 10500",
    Imgsrc: require("./files/boltbolt.webp"),
    link: "",
    visit: "bolt-bolt",
    desc: "",
  },
  {
    key: 16,
    name: "lumentrace",
    prize: "₹ 10500",
    Imgsrc: require("./files/lumentrace.webp"),
    link: "",
    visit: "lumen-trace",
    desc: "",
  },
  {
    key: 17,
    name: "smart tank",
    prize: "₹ 10500",
    Imgsrc: require("./files/smarttank.webp"),
    link: "",
    visit: "smart-tank",
    desc: "",
  },
  {
    key: 18,
    name: "CHEM-E-CODE",
    prize: "₹ 5000",
    Imgsrc: require("./files/smarttank.webp"),
    link: "",
    visit: "chem-e-code",
    desc: "In this event, the participant will be given a chemical engineering problem which needs to be solved using...",
  },
  {
    key: 19,
    name: "SCUFFLE",
    prize: "Momentos+",
    Imgsrc: require("./files/smarttank.webp"),
    link: "",
    visit: "smarttank",
    desc: "A race which consists of 5 hurdles which helps to check the presence of mind of participants....",
  },
  {
    key: 20,
    name: "trickycircuits",
    prize: "₹ 5000",
    Imgsrc: require("./files/trickycircuits.webp"),
    link: "",
    visit: "trickycircuits",
    desc: "Tricky Circuits is a competition where participants will be given circuits consisting of resistors, gates, and ...",
  },
];

export const teamData = [
  {
    key: 1,
    name: "XYZ",
    role: "Faculty",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 2,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 3,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 4,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
];

export const fashionShowdata = [
  {
    key: 1,
    image: require("./assets/images/fashion-show/1.jpg"),
  },
  {
    key: 2,
    image: require("./assets/images/fashion-show/2.jpg"),
  },
  {
    key: 3,
    image: require("./assets/images/fashion-show/3.jpg"),
  },
  {
    key: 4,
    image: require("./assets/images/fashion-show/4.jpg"),
  },
  {
    key: 5,
    image: require("./assets/images/fashion-show/5.jpg"),
  },
  {
    key: 6,
    image: require("./assets/images/fashion-show/6.jpg"),
  },
];
