export const data = [
  {
    key: 1,

    name: "Hackathon",
    prize: "60000",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "https://hackmol.tech/",
    visit: "https://hackmol.tech/",
    desc: "HackMOL is the flagship annual 30-hour hackathon being organised by GDSC of NIT J...",
  },
  {
    key: 2,
    name: "Fashion Show",
    prize: "30000",
    Imgsrc: require("./files/fashion.webp"),
    link: "https://forms.gle/1yoLPcBeK3oidNxC9",
    visit: "event/fashionshow",
    desc: "Fashion show organised by NITJ is one of the most awaited and celebrated events of TechNITi ....",
  },
  {
    key: 3,
    name: "NITYaan",
    prize: "10000",
    Imgsrc: require("./files/nityaan.webp"),
    link: "register",
    visit: "event/nityaan",
    desc: "NIT, Jalandhar is back with NITYAAN, catered to quench the thirst of rocket enthusiasm among...",
  },
  {
    key: 4,
    name: "robowar",
    prize: "45000",
    Imgsrc: require("./files/robowars.webp"),
    link: "https://forms.gle/JfnzxkCG6GF4iwGM8",
    visit: "event/robowar",
    desc: "It will be a savage, Clash of Metals with the alloys grindingred hot. It is a game of style, control, damage and aggression  ... ",

    // name: "2-day Workshops",
    // prize: "Internships & Certificates",
    // Imgsrc: require("./files/workshop.webp"),
    // link: "https://forms.gle/k5BuoSoYThWQUXmWA",
    // visit: "event/workshop",
    // desc: "In hand practical Workshops on Ethical Hacking and Blockhain, get an intern oppurtunity with startup...",
  },
  {
    key: 5,
    name: "uav-drone",
    prize: "25000",
    Imgsrc: require("./files/UAVdrone.webp"),
    link: "https://forms.gle/wCzafoX9d3NbdEQh7",
    visit: "event/uavdrone",
    desc: "Drones are objects that the world is looking up to. TechNITi'23 presents the UAV Drone challange, A multi-level ...",
  },
  {
    key: 6,
    name: "robohunt",
    prize: "3000",
    Imgsrc: require("./files/robohunt.webp"),
    link: "https://forms.gle/UEAWkhwVnsAxkMkB8",
    visit: "event/robohunt",
    desc: "Robo Hunt is a competition where teams will write the code of controller of small robots, known as bots, that are less than 6 kg...",
  },
  {
    key: 7,
    name: "microrobowar",
    prize: "8000",
    Imgsrc: require("./files/microrobowar.webp"),
    link: "https://forms.gle/UEAWkhwVnsAxkMkB8",
    visit: "event/microrobowar",
    desc: "Micro Robo War is a robot fighting competition where contestant teams will compete head-to-head in a 1 vs 1 match...",
  },

  {
    key: 8,
    name: "chem-e-car",
    prize: "10000",
    Imgsrc: require("./files/chemecar.webp"),
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfro6E2c-CIl6NMzhWu2Qf-2N0a-9BRlM5KtiPN0nFLs0vftA/viewform?usp=sf_link",
    visit: "event/chem-e-car",
    desc: "Chem-e-car involves students designing and constructing a car  powered by any chemical energy source that will ...",
  },
  {
    key: 9,
    name: "Squad of the year",
    prize: "8000",
    Imgsrc: require("./files/squadoftheyear.webp"),
    link: "http://surl.li/euwiw",
    visit: "event/squadoftheyear",
    desc: `When worst comes to worst, my squad comes first.  Look through the canon...`,
  },

  {
    key: 10,
    name: "Green Tecton",
    prize: "8600",
    Imgsrc: require("./files/greentecton.webp"),
    link: "https://docs.google.com/forms/d/1TLwq6oO2DsrhBT_tDFFrRaa_t8cL_Cv7mlucgciLk3E/edit",
    visit: "event/greentecton",
    desc: "The core aim of the project is to provide a Structure design of 250yd (standard urban house size) plot size 30’X75’...",
  },
  {
    key: 11,
    name: "prayaas",
    prize: "",
    Imgsrc: require("./files/prayaas.webp"),
    link: "prayaasregister",
    visit: "event/prayaas",
    desc: "To educate underprivileged and socially marginalized youth who lack access to education, especially those who are the...",
  },
  {
    key: 12,
    name: "chem-e-design",
    prize: "10000",
    Imgsrc: require("./files/chemedesign.webp"),
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfro6E2c-CIl6NMzhWu2Qf-2N0a-9BRlM5KtiPN0nFLs0vftA/viewform?usp=sf_link",
    visit: "event/chem-e-design",
    desc: "The event will involve designing a highly efficient and leakage proof heat exchanger and then...",
  },
  {
    key: 13,
    name: "RCcars",
    prize: "14000",
    Imgsrc: require("./files/rccar.webp"),
    link: "https://forms.gle/qvxPaHiwoxFEmH457",
    visit: "event/rccars",
    desc: "The basic task is to Design and make a wireless or wired Remote Controlled (RC) Car Powered by batteries and using a DC motor ...",
  },
  {
    key: 14,
    name: "atv Racing",
    prize: "",
    Imgsrc: require("./files/atv.webp"),
    link: "register",
    visit: "event/avishkar",
    desc: "Our self-manufactured ATV is exhibited in fully running condition and workshop would be commanded by various...",
  },
  {
    key: 15,
    name: "CHEM-E-HUNT",
    prize: "3000",
    Imgsrc: require("./files/chemehunt.webp"),
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfro6E2c-CIl6NMzhWu2Qf-2N0a-9BRlM5KtiPN0nFLs0vftA/viewform?usp=sf_link",
    visit: "event/chem-e-hunt",
    desc: "Chem -e- hunt is a treasure hunt in which  numericals related to chemical engineering will be asked ...",
  },
  {
    key: 16,
    name: "bolt-bolt",
    prize: "15000",
    Imgsrc: require("./files/boltbolt.webp"),
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfQgPcII4r-kYbSFE2TYXoTnQj1QyoP6aNZdaC8q5-XsIlHzw/viewform?usp=sf_link",
    visit: "event/bolt-bolt",
    desc: "It is a competition in which a team of 4 has to make a remote controlled robot car which has to race with other ...",
  },
  {
    key: 17,
    name: "lumen trace",
    prize: "10500",
    Imgsrc: require("./files/lumentrace.webp"),
    link: "https://forms.gle/GdCrimFcpytXpT7t6",
    visit: "event/lumen-trace",
    desc: "In this competition a team of 4 has to create a color sensing robot which will be placed on an arena with different ...",
  },
  {
    key: 18,
    name: "smart tank",
    prize: "6000",
    Imgsrc: require("./files/smarttank.webp"),
    link: "https://forms.gle/qmUzgT4cKcR4hzG59",
    visit: "event/smart-tank",
    desc: "It is a ideation competition in which participants have to pitch their unique ideas or projects in the field of iot or robotics",
  },

  {
    key: 19,
    name: "Best from waste",
    prize: "5000",
    Imgsrc: require("./files/bestfromwaste.webp"),
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfro6E2c-CIl6NMzhWu2Qf-2N0a-9BRlM5KtiPN0nFLs0vftA/viewform?usp=sf_link",
    visit: "event/best-from-waste",
    desc: "The event will involve crafting environmental friendly and engineering based prototypes by recycling the waste materials....",
  },
  {
    key: 20,
    name: "trickycircuits",
    prize: "5000",
    Imgsrc: require("./files/trickycircuits.webp"),
    link: "https://forms.gle/UEAWkhwVnsAxkMkB8",
    visit: "event/trickycircuits",
    desc: "Tricky Circuits is a competition where participants will be given circuits consisting of resistors, gates, and ...",
  },
  {
    key: 21,
    name: "gaNIT",
    prize: "5000",
    Imgsrc: require("./files/maths.webp"),
    link: "https://forms.gle/yZDDpBLV5oM4YCQ3A",
    visit: "event/integrationbee",
    desc: "The Integration Bee is an annual traditional playoff-style event that has gained popularity in US colleges and universities...",
  },
  {
    key: 22,
    name: "BE INQUISITIVE",
    prize: "5000",
    Imgsrc: require("./files/beinquisitive.webp"),
    link: "https://forms.gle/8xGzkNPt8FdkwvDx9",
    visit: "event/beinquisitive",
    desc: "The objective behind this competition is to evaluate the knowledge of the participants within academics as well...",
  },
  {
    key: 23,
    name: "AD MAD SHOW",
    prize: "5000",
    Imgsrc: require("./files/admadshow.webp"),
    link: "https://forms.gle/8xGzkNPt8FdkwvDx9",
    visit: "event/admadshow",
    desc: "Group of 3-4 students, will be asked to create a marketing plan including creating a full-fledged creative ...",
  },
  {
    key: 24,
    name: "Leadership & Mentoring",
    prize: "5000",
    Imgsrc: require("./files/leadershipandmentoring.webp"),
    link: "https://forms.gle/8xGzkNPt8FdkwvDx9",
    visit: "event/leadershipandmentoring",
    desc: "The objective behind this competition is to evaluate the individuals' leadership, presentation ...",
  },
];

export const teamData = [
  {
    key: 1,
    name: "XYZ",
    role: "Faculty",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 2,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 3,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
  {
    key: 4,
    name: "XYZ",
    role: "",
    img: "https://picsum.photos/200/200",
    linkedin: "https://www.linkedin.com",
    insta: "https://www.instagram.com/",
  },
];

export const fashionShowdata = [
  {
    key: 1,
    image: require("./assets/images/fashion-show/1.jpg"),
  },
  {
    key: 2,
    image: require("./assets/images/fashion-show/2.jpg"),
  },
  {
    key: 3,
    image: require("./assets/images/fashion-show/3.jpg"),
  },
  {
    key: 4,
    image: require("./assets/images/fashion-show/4.jpg"),
  },
  {
    key: 5,
    image: require("./assets/images/fashion-show/5.jpg"),
  },
  {
    key: 6,
    image: require("./assets/images/fashion-show/6.jpg"),
  },
];
